---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/medicos":
    get:
      summary: View a list of available medicos
      tags:
      - Medicos
      responses:
        '200':
          description: successful
    post:
      summary: Add a medico
      tags:
      - Medicos
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                photo:
                  type: string
                password:
                  type: string
                phone:
                  type: string
              required:
              - email
              - name
              - password
  "/medicos/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: Get a medico by id
      tags:
      - Medicos
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  name:
                    type: string
                  photo:
                    type: string
                  password:
                    type: string
                  phone:
                    type: string
                required:
                - id
                - email
                - name
                - password
                example:
                  id: 1
                  email: dr.john.doe@example.com
                  name: Dr. John Doe
                  photo: dr_john_doe.jpg
                  password: password123
                  phone: 123-456-7890
        '404':
          description: not found
    patch:
      summary: Update a medico
      tags:
      - Medicos
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                photo:
                  type: string
                password:
                  type: string
                phone:
                  type: string
              required:
              - email
              - name
              - password
              example:
                email: dr.john.doe@example.com
                name: Dr. John Doe
                photo: dr_john_doe.jpg
                password: password123
                phone: 123-456-7890
    delete:
      summary: Delete a medico
      tags:
      - Medicos
      responses:
        '204':
          description: no content
        '404':
          description: not found
servers:
- url: http://127.0.0.1:3000
  variables:
    defaultHost:
      default: 127.0.0.1:3000
